[features]
seeds = false
skip-lint = false
[programs.devnet]
moneymannage = "A7zNPvGup3CLHhgghEDPRWRhNwJJz2QkyEXnvABMDpQ8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Create.ts"
check = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/check.ts"